version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_React
    container_name: react_web
    command: yarn dev
    image: react_front
    ports:
     - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    environment:
      NODE_ENV: development

